trigger:
- main   # Runs pipeline when changes are pushed to the 'main' branch
- master

pool:
  name: my-agent             #agent pool name
  demands:
    - Agent.Name -equals azure-devops-agent    #agent name

steps:                                          #jobs to run
- script: echo "Hello World"
  displayName: 'Run Hello World script'


- script: echo "code is building"              #actual script that will be executed on azure agent
  displayName: 'build code job'                #this name will appear on azure devops
